// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_content_delivery_bucket": "railroad-editor-20190824171919-hostingbucket-test",
    "aws_content_delivery_bucket_region": "ap-northeast-1",
    "aws_content_delivery_url": "http://railroad-editor-20190824171919-hostingbucket-test.s3-website-ap-northeast-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "ap-northeast-1:70b328a2-6f72-46ea-8a9a-dc4729744f21",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_mYQhoEzeH",
    "aws_user_pools_web_client_id": "1m7vhfak79i1296nkehr577n7o",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "layout",
            "endpoint": "https://lxbxs0yn99.execute-api.ap-northeast-1.amazonaws.com/test",
            "region": "ap-northeast-1"
        },
        {
            "name": "issue",
            "endpoint": "https://nqgvi6yd3g.execute-api.ap-northeast-1.amazonaws.com/test",
            "region": "ap-northeast-1"
        },
        {
            "name": "session",
            "endpoint": "https://pug06oe7h9.execute-api.ap-northeast-1.amazonaws.com/test",
            "region": "ap-northeast-1"
        }
    ],
    "aws_dynamodb_all_tables_region": "ap-northeast-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "layouts-test",
            "region": "ap-northeast-1"
        },
        {
            "tableName": "sessions-test",
            "region": "ap-northeast-1"
        }
    ],
    "aws_user_files_s3_bucket": "railroad-editor-user-files-test",
    "aws_user_files_s3_bucket_region": "ap-northeast-1",
    "aws_cloud_logic": "enable",
    "aws_content_delivery": "enable",
    "aws_content_delivery_cloudfront": "enable",
    "aws_content_delivery_cloudfront_domain": "d2v8bu4e76jqt1.cloudfront.net",
    "aws_project_id": "afb78a90-fb33-4b35-aabb-2be1304f8015",
    "aws_project_name": "railroad-editor",
    "aws_resource_name_prefix": "railroadeditor-mobilehub-69379349",
    "aws_sign_in_enabled": "enable",
    "aws_user_files": "enable",
    "aws_user_pools": "enable"
};


export default awsmobile;
