// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_content_delivery_bucket": "railroad-editor-20190824171919-hostingbucket-prod",
    "aws_content_delivery_bucket_region": "ap-northeast-1",
    "aws_content_delivery_url": "http://railroad-editor-20190824171919-hostingbucket-prod.s3-website-ap-northeast-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "ap-northeast-1:d5874b97-c161-415e-89e3-e6b46a2580b9",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_GUllp0rXg",
    "aws_user_pools_web_client_id": "6sp9ukc4nhin2otj1dm3v2m0lp",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "layout",
            "endpoint": "https://yt681qbok8.execute-api.ap-northeast-1.amazonaws.com/prod",
            "region": "ap-northeast-1"
        }
    ],
    "aws_app_analytics": "enable",
    "aws_cloud_logic": "enable",
    "aws_content_delivery": "enable",
    "aws_content_delivery_cloudfront": "enable",
    "aws_content_delivery_cloudfront_domain": "d2v8bu4e76jqt1.cloudfront.net",
    "aws_mobile_analytics_app_id": "989b8b385f0147ee9c77e34caac43e50",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_project_id": "afb78a90-fb33-4b35-aabb-2be1304f8015",
    "aws_project_name": "railroad-editor",
    "aws_resource_name_prefix": "railroadeditor-mobilehub-69379349",
    "aws_sign_in_enabled": "enable",
    "aws_user_files": "enable",
    "aws_user_files_s3_bucket": "railroadeditor-userfiles-mobilehub-69379349",
    "aws_user_files_s3_bucket_region": "ap-northeast-1",
    "aws_user_pools": "enable"
};


export default awsmobile;
