// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"foo866bgvk","name":"Layout","description":"","endpoint":"https://foo866bgvk.execute-api.ap-northeast-1.amazonaws.com/beta","region":"ap-northeast-1","paths":["/","/confirm","/users/{userId}/layouts","/users/{userId}/layouts/{layoutId}","/users/{userId}/session"]}],
    'aws_cognito_identity_pool_id': 'ap-northeast-1:047463f2-70ee-4de1-925c-f75f46ae67a8',
    'aws_cognito_region': 'ap-northeast-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'railroadeditor-hosting-mobilehub-69379349',
    'aws_content_delivery_bucket_region': 'ap-northeast-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd2v8bu4e76jqt1.cloudfront.net',
    'aws_mobile_analytics_app_id': '989b8b385f0147ee9c77e34caac43e50',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'afb78a90-fb33-4b35-aabb-2be1304f8015',
    'aws_project_name': 'railroad-editor',
    'aws_project_region': 'ap-northeast-1',
    'aws_resource_name_prefix': 'railroadeditor-mobilehub-69379349',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'railroadeditor-userfiles-mobilehub-69379349',
    'aws_user_files_s3_bucket_region': 'ap-northeast-1',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'ap-northeast-1_SW4VnlrmO',
    'aws_user_pools_web_client_id': '6dedi9vc5b14dijcfeomuhfdav',
}

export default awsmobile;
